# -*- mode: Org; ispell-local-dictionary: "brasileiro"; -*-
#+TITLE: Classe LaTeX para Trabalhos Acadêmicos do Ifes
#+AUTHOR: Jefferson O. Andrade
#+OPTIONS: toc:nil

Este repositório contém a implementação de uma classe \LaTeX{} para trabalhos
acadêmicos em conformidade com as 
/“Normas para Apresentação de Trabalhos Acadêmicos e Científicos: Documento Impresso e/ou Digital”/, 
*8ª edição revista e ampliada*, de Novembro de 2017 do /Instituto Federal do Espírito Santo/ (Ifes). 
A classe possibilita a criação de um trabalho acadêmico completo, com inserção de
elementos pré-textuais (capa, folha de rosto, ficha catalográfica, epígrafe,
dedicatória, sumário e listas de figuras, tabelas, algoritmos, siglas e
símbolos), passando pelo corpo do texto e elementos pós-textuais (índice
remissivo, referências bibliográficas, apêndices e anexos).

A classe =ifes8= é essencialmente uma customização da classe
=abntex2= juntamente com a inclusão e pré-configuração de alguns
pacotes adicionais, necessários para implementar as normas do Ifes.
Assim sendo, esta classe depende da classe =abntex2=.

No manual, os usuários encontrarão informações sobre a utilização
desta classe, seus comandos e algumas boas práticas para que o
trabalho fique no formato desejado pela biblioteca.


* Instalação

A versão mais recente da classe pode sempre ser encontrada no GitHub, no
endereço [[https://github.com/quigonjeff/ifes8]].

Considerando que a instalação \LaTeX{} do usuário já contenha a classe
=abntex2=, basta copiar o arquivo =ifes8.cls= para o mesmo diretório que o
arquivo principal do seu projeto.


* Utilização

A classe pode ser usada adicionando a linha

#+BEGIN_SRC tex
\documentclass[12pt,times,a4paper,english,brazil,
chapter=TITLE,section=TITLE,subsection=TITLE]{ifes8}
#+END_SRC

no início do documento LaTeX. O manual descreve as funcionalidades da
classe. Dois modelos básicos prontos para compilação e alteração são
disponibilizados no repositório.

*Importante:* Note que, até o momento, nem todas as formatações foram incluídas
na classe, portanto é importante que o usuário consulte o exemplo dado e siga a
mesma estrutura. E *não remova* nenhum dos comandos que são definidos dentro do
exemplo.


* Licença

Released under the LaTeX Project Public License v1.3c or later See
<http://www.latex-project.org/lppl.txt>.


